services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: senteur_app
    volumes:
      - ./:/var/www
      - /var/www/vendor
      - product_uploads:/var/www/public/uploads

  nginx:
    image: nginx:alpine
    container_name: senteur_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - product_uploads:/var/www/public/uploads:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: senteur_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: senteur
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql_data:
  product_uploads: