services:
  app:
    volumes:
      - ./:/var/www:z

  nginx:
    volumes:
      - ./:/var/www:z
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,z

  mysql:
    volumes:
      - mysql_data:/var/lib/mysql:z
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro,z